export const projects = [

  // Web and App Projects
  {
    id: 1,
    title: "HCSES",
    subtitle: "Events Management System",
    description: "A MERN(MongoDB, Express JS, React JS, Node JS) stack based event booking system developed for my school project, tailored for Harvest’s Catering and Event Styling business.",
    type: "webandapp",
    typeLabel: "Website(Team Project)",
    emoji: "",
    tags: ["MongoDB", "Express JS", "React", "Node JS", "Chakra UI"],
    liveUrl: "#",
    codeUrl: "#",
    featured: true,
    images: [
      { src: HCSES1, caption: "Dashboard" },
      { src: HCSES2, caption: "Package Page" },
      { src: HCSES3, caption: "Food Menu Page" },
      { src: HCSES4, caption: "Why Choose Us Page" },
      { src: HCSES5, caption: "Feedbacks and Reviews Page" },
      { src: HCSES6, caption: "Feedbacks and Reviews Page" },
      { src: HCSES7, caption: "Contacts Page" },
      { src: HCSES8, caption: "Add Event Page" },
      { src: HCSES9, caption: "Admin Dashboard" },
      { src: HCSES10, caption: "Transaction History Page" },
      { src: HCSES11, caption: "Order List Page" },
      { src: HCSES12, caption: "Approval Page" },
      { src: HCSES13, caption: "Approval Page" },
      { src: HCSES14, caption: "Approval Page" },
      { src: HCSES15, caption: "Analytics Page" },
      { src: HCSES16, caption: "Admin Sign-in Page" },
      { src: HCSES17, caption: "Admin Sign-up Page" },
    ],
  },
  {
    id: 2,
    title: "Note Nest",
    subtitle: "Personal Note-Taking App",
    description: "A React Native note taking application used to record various notes with private notes feature (with passwords) and To-Do.",
    type: "webandapp",
    typeLabel: "Application",
    emoji: "",
    tags: ["React Native"],
    liveUrl: "#",
    codeUrl: "#",
    featured: true,
    images: [
      { src: NoteNest1, caption: "Private Notes Screen" },
      { src: NoteNest2, caption: "Personal Notes Screen" },
      { src: NoteNest3, caption: "Personal Sunday Service Notes Screen" },
      { src: NoteNest4, caption: "Notes Editor Screen" },
      { src: NoteNest5, caption: "To Do List Screen" },
      { src: NoteNest6, caption: "Profile Screen" },
    ],
  },
    {
    id: 3,
    title: "Pytrinian",
    subtitle: "A Reinforcement Learning-based Tutor for Programming Language",
    description: "A Reinforcement Learning-based Intelligent Tutoring System for Python programming education, built on a FERN stack with a FastAPI reinforcement learning server and an LLM-powered question generation pipeline.",
    type: "webandapp",
    typeLabel: "Website(Team Project)",
    emoji: "",
    tags: ["Firebase", "Express JS", "React JS", "Node JS", "FastAPI", "Python", "Material UI", "Ollama", "Qwen2.5b", "LangChain" , "Stable-baselines3", "PPO Algorithm"],
    liveUrl: "#",
    codeUrl: "#",
    featured: true,
    images: [
      { src: Pytrinian1, caption: "User Dashboard" },
      { src: Pytrinian2, caption: "Topics Page" },
      { src: Pytrinian3, caption: "Activity Page" },
      { src: Pytrinian4, caption: "Results Modal" },
      { src: Pytrinian5, caption: "Analytics Page" },
      { src: Pytrinian6, caption: "Coding Playground Page" },
      { src: Pytrinian7, caption: "Discussion Page" },
      { src: Pytrinian8, caption: "User Guide" },
      { src: Pytrinian9, caption: "Sign-in Page" },
    ],
  },
    {
    id: 4,
    title: "Saved Worship Music Tool",
    subtitle: "Events Management System",
    description: "A React Native application designed for our local church to manage team and various music related resources.",
    type: "webandapp",
    typeLabel: "Application",
    emoji: "",
    tags: ["React Native", "Supabase"],
    liveUrl: "#",
    codeUrl: "#",
    featured: true,
    images: [
      { src: SavedWorshipMusicTool1, caption: "Chords Library Screen" },
      { src: SavedWorshipMusicTool2, caption: "Chords Playlist Screen" },
      { src: SavedWorshipMusicTool3, caption: "Chords and Lyrics Viewer" },
      { src: SavedWorshipMusicTool4, caption: "Viewer Additional Tools" },
      { src: SavedWorshipMusicTool5, caption: "Notes Page" },
      { src: SavedWorshipMusicTool6, caption: "Line Up Page" },
      { src: SavedWorshipMusicTool7, caption: "Line Up Viewer" },
      { src: SavedWorshipMusicTool8, caption: "Other Announcements Page" },
      { src: SavedWorshipMusicTool9, caption: "Conversation Page" },
      { src: SavedWorshipMusicTool10, caption: "Drawer" },
      { src: SavedWorshipMusicTool11, caption: "Edit Profile Page" },
      { src: SavedWorshipMusicTool12, caption: "Edit Profile Page" },
      { src: SavedWorshipMusicTool13, caption: "Team Schedule Management" },
      { src: SavedWorshipMusicTool14, caption: "Team Schedule Management" },
      { src: SavedWorshipMusicTool15, caption: "Metronome Page" },
      { src: SavedWorshipMusicTool16, caption: "Metronome Page" },
      { src: SavedWorshipMusicTool17, caption: "Manual Transpose Page" },
      { src: SavedWorshipMusicTool18, caption: "Sign-in Page" },
      { src: SavedWorshipMusicTool19, caption: "Sign-up Page" },
    ],
  },
      {
    id: 5,
    title: "Shiori",
    subtitle: "Anime, Manga, and Light Novel Tracking App",
    description: "A React Native mobile application for tracking anime, light novel, and manga, featuring AniList integration for metadata, personal watchlists, and reading progress management.",
    type: "webandapp",
    typeLabel: "Application",
    emoji: "",
    tags: ["React Native", "Supabase", "Anilist API"],
    liveUrl: "#",
    codeUrl: "#",
    featured: true,
    images: [
      { src: Shiori1, caption: "Anime List Screen" },
      { src: Shiori2, caption: "Manga List Screen" },
      { src: Shiori3, caption: "Light Novel List Screen" },
      { src: Shiori4, caption: "Discover Page" },
      { src: Shiori5, caption: "Drawer" },
      { src: Shiori6, caption: "Library Page" },
      { src: Shiori7, caption: "Anime Song Playlist" },
      { src: Shiori8, caption: "Creator List Page" },
      { src: Shiori9, caption: "Creator's List of Works Page" },
      { src: Shiori10, caption: "Anime/Manga/Light Novel Details Page" },
      { src: Shiori11, caption: "Anime/Manga/Light Novel Details Page" },
      { src: Shiori12, caption: "Anime/Manga/Light Novel Details Page" },
      { src: Shiori13, caption: "Anime/Manga/Light Novel Details Page" },
    ],
  },

// Game Projects
{
  id: 6,
  title: "Breademption",
  subtitle: "Typing Game",
  description: "In Breademption, you must defend the last remaining loaf of bread in a world overrun by germs, using typing as your weapon. Throughout the game, a random letter will be banned as an added challenge, but you can change the banned letter whenever you need to. Breademption is a fast-paced typing defense game where quick thinking and adaptability are key to survival.",
  type: "game",
  typeLabel: "Game",
  emoji: "",
  tags: ["Godot", "GDScript"],
  itchUrl: "https://svojii.itch.io/breademption",
  featured: false,
  logo: BreademptionLogo,
  images: [
    { src: Breademption1, caption: "Main Screen" },
    { src: Breademption2, caption: "Gameplay" },
    { src: Breademption3, caption: "Gameplay" },
    { src: Breademption4, caption: "Gameplay" },
    { src: Breademption5, caption: "Gameplay" },
  ],
},
{
  id: 7,
  title: "Staffocalypse",
  subtitle: "Color Shooting Game",
  description: "Staffocalypse is a fast-paced elemental color shooting game where survival depends on mastering elemental reactions. You are a mage wielding a powerful staff capable of shooting different elemental orbs. Combine elements, trigger powerful reactions, manage your energy wisely, and eliminate waves of enemies before they overwhelm you. Balance power and precision, or face the apocalypse.",
  type: "game",
  typeLabel: "Game",
  emoji: "",
  tags: ["Godot", "GDScript"],
  itchUrl: "https://svojii.itch.io/staffocalypse",
  featured: false,
  logo: StaffocalypseLogo,
  images: [
    { src: Staffocalypse1, caption: "Main Screen" },
    { src: Staffocalypse2, caption: "Gameplay" },
    { src: Staffocalypse1, caption: "Gameplay" },
  ],
},

// Digital Art project 
{
  id: 8,
  title: "Varesa (Genshin Impact)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Varesa, a character from Genshin Impact, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece1, caption: "Varesa (Genshin Impact)" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Kaoruko Waguri",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Kaoruko Waguri, a character from Fragrant Flowers Blooms with Dignity, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece2, caption: "Kaoruko Waguri" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Columbina (Genshin Impact)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Columbina, a character from Genshin Impact, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece3, caption: "Columbina (Genshin Impact)" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Hanako-kun",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Hanako-kun, a character from Toilet bound Hanako-kun, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece4, caption: "Hanako-kun" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "HuTao (Genshin Impact)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of HuTao, a character from Genshin Impact, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece5, caption: "HuTao (Genshin Impact)" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Monica Everett",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Monica Everett, a character from The Secrets of the Silent Witch, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece6, caption: "Monica Everett" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Von Lycaon (ZZZ)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Von Lycaon, a character from ZZZ, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece7, caption: "Von Lycaon (ZZZ)" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Diluc (Genshin Impact)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Diluc, a character from Genshin Impact, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece8, caption: "Diluc (Genshin Impact)" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Kaoruko Waguri",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Kaoruko Waguri, a character from Fragrant Flowers Blooms with Dignity, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece9, caption: "Kaoruko Waguri" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Luffy",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Luffy, a character from One Piece, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece10, caption: "Luffy" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Random Chibi",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of a random chibi character, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece11, caption: "Random Chibi" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Kaedehara Kazuha Chibi Version (Genshin Impact)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Kaedehara Kazuha, a character from Genshin Impact, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece12, caption: "Kaedehara Kazuha Chibi Version (Genshin Impact)" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Roxy Migurdia",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Roxy Migurdia, a character from Mushoku Tensei, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece13, caption: "Roxy Migurdia" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Raiden Shogun (Genshin Impact)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Raiden Shogun, a character from Genshin Impact, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece14, caption: "Raiden Shogun (Genshin Impact)" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Alisa Mikhailovna Kujou",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Alisa Mikhailovna Kujou, a character from Alya-san Sometimes Hides her Feelings on Russian, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece15, caption: "Alisa Mikhailovna Kujou" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Akane Kinoshita",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Akane Kinoshita, a character from My Love Story with Yamada-kun at Lv999, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece16, caption: "Akane Kinoshita" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Anna Yanami",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Anna Yanami, a character from Makeine, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece17, caption: "Anna Yanami" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Hitori Gotoh",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Hitori Gotoh, a character from Bocchi the Rock!, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece18, caption: "Hitori Gotoh" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Hitori Gotoh",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Hitori Gotoh, a character from Bocchi the Rock!, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece19, caption: "Hitori Gotoh" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Kita Ikuyo",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Kita Ikuyo, a character from Bocchi the Rock!, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece20, caption: "Kita Ikuyo" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Crazy Mita (MiSide)",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Crazy Mita (MiSide), a character from the game MiSide, created using Clip Studio Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece21, caption: "Crazy Mita (MiSide)" },
  tags: ["Clip Studio Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Nijika Ijichi",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Nijika Ijichi, a character from Bocchi the Rock!, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece22, caption: "Nijika Ijichi" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
{
  id: 8,
  title: "Ryou Yamada",
  subtitle: "Digital Illustration",
  description: "Character Ilustration of Ryou Yamada, a character from Bocchi the Rock!, created using Ibis Paint.",
  type: "art",
  typeLabel: "Digital Art",
  image: { src: ArtPiece23, caption: "Ryou Yamada" },
  tags: ["Ibis Paint", "Character Design"],
  featured: false,
},
];
svojii.itch.io